### ISSUE TITLE
Different results compared to previous papers.

### ISSUE THREAD

**Issue by yanzhangnlp** [AmitMY/chimera#6]
Hi Amit,

Thanks for your great work.  I am wondering why your baseline results (Melbourne) in Table 1 are different from the scores mentioned in their paper [1]. Besides, there is a paper doing the same dataset, from University of Edinburgh [2]. Did you consider the comparison with them? Thanks

[1] Trisedya, Bayu Distiawan, et al. "GTR-LSTM: A Triple Encoder for Sentence Generation from RDF Data." ACL2018
[2] Diego Marcheggiani, Laura Perez-Beltrachini. Deep Graph Convolutional Encoders for Structured Data to Text Generation. INLG 2018

**Comment by AmitMY** [comment]
Hi Zhang,
I wasn't familiar with the first paper. When I contacted the author last year, they also said the only report is what published with the WebNLG challenge results.
As for their results: They claim to have the best model, but I couldn't find any dataset overall metrics. (only split on seen and unseen). 
Furthermore, the WebNLG report (http://webnlg.loria.fr/pages/webnlg-challenge-report.pdf) reports the best "seen" system as ADAPT, and regards to unseen, our method, and our neural end-to-end baseline are better.
A final note is to say that in their error analysis, they talk about 8% error rate, in general, and our model is at ~5%, but it is pretty hard to compare as they do not go in length on how they performed their error analysis.
(Not to dis their work, of course, it is very interesting, and I would probably try entity-masking to see how it works)

Regarding the second paper, which is the first "different" method, I became aware of it after finishing to write the paper (12 pages instead of 9), and couldn't cram it in. Purely incompetence on my part.

**Comment by yanzhangnlp** [comment]
I see, thanks for your prompt reply!
